<!-- Dmahugh scaffolding for web apps - modified version of Boostrap starter file -->
<!-- originally downloaded from http://getbootstrap.com/getting-started/#template -->
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- These 3 meta tags *must* come first in the head -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="image/favicon.ico">

    <title>scaffolding-dmahugh</title>

    <!-- Bootstrap core CSS -->
    <!-- <link href="css/bootstrap.min.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    <!-- Bootstrap theme -->
    <!-- <link href="css/bootstrap-theme.min.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

    <!-- custom CSS styles for this app-->
    <!-- <link href="css/style.css" rel="stylesheet"> -->
    <link href="http://mahugh.com/js/scaffolding/css/style.css" rel="stylesheet">
    <!-- custom JavaScript for this app -->
    <!-- <script src="js/script.js"></script> -->
    <script src="http://mahugh.com/js/scaffolding/js/script.js"></script>

    <!-- provide IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body role="document">

<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
                <span>Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="#"><img src="image/navbar-brand.jpg"></a>

        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#contact">Contact</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action #1</a></li>
                        <li><a href="#">Action #2</a></li>
                        <li><a href="#">Action #3</a></li>
                        <li class="divider"></li>
                        <li class="dropdown-header">dropdown-header</li>
                        <li><a href="#">Action #4</a></li>
                        <li><a href="#">Action #5</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container theme-showcase" role="main">
    <?= $this->content; ?>
</div>

<!-- external JavaScript at end of document for faster page load -->
<!-- <script src="js/holder.js"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/holder/2.6.0/holder.min.js"></script>

<!-- <script src="js/jquery-1.11.2.js"></script> -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

<!-- <script src="js/bootstrap.min.js"></script> -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

<script>
    $(document).ready(function () {
        $('#jqueryVersion').text(jQuery.fn.jquery);
    });
</script>

</body>
</html>